server:
  port: 7002

spring:
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端名称
  client:
    #表示不注册自己
    register-with-eureka: false
    #表示自己是注册中心
    fetch-registry: false
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7001.com:7001/eureka/
      #单机就是7001自己
      defaultZone: http://eureka7002.com:7002/eureka/